(function(){
  const store=window.ESPANStore,user=store.currentUser();
  if(!user){location.replace("auth.html#loginSection");return}
  const id=Number(new URLSearchParams(location.search).get("id"))||1,p=store.data.products.find(x=>Number(x.id)===id),page=document.getElementById("productPage");
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const money=n=>new Intl.NumberFormat("ar-LY").format(Math.round(n||0))+" د.ل";
  if(!p){page.innerHTML='<div class="not-found"><h1>المنتج غير موجود</h1><a href="account.html">الرجوع للعروض</a></div>';return}
  const pricing=store.priceInfo(p,1),available=p.quantity>0,frames=p.frames?.length?p.frames:[p.image],reviews=(store.data.reviews||[]).filter(r=>Number(r.productId)===Number(p.id));
  page.innerHTML=`<div class="detail-grid"><section><div class="viewer" id="viewer"><span class="angle" id="angle">0°</span><img id="productImage" src="${esc(p.image)}" alt="عرض 360 درجة لـ ${esc(p.name)}" draggable="false"><span class="hint">${frames.length>1?"اسحبي الصورة بيدك يمينًا ويسارًا لتدويرها 360°":"صورة المنتج الرئيسية"}</span></div></section><section class="details"><span class="eyebrow">${esc(p.category||"تفاصيل المنتج")}</span><h1>${esc(p.name)}</h1><p class="description">${esc(p.description)} يمكن تنفيذ المقاس واللون بما يناسب مساحتك بعد مراجعة الطلب.</p><span class="price" id="unitPrice">${money(p.price)}</span>${pricing.offer?`<span class="offer-label" id="offerLabel">${esc(pricing.offer.title)} — ${pricing.offer.type==="percentage"?`خصم ${pricing.offer.value}%`:`خصم ${money(pricing.offer.value)}`} ${Number(pricing.offer.minQuantity||1)>1?`عند شراء ${pricing.offer.minQuantity} قطع أو أكثر`:`من أول قطعة`}</span>`:""}<span class="stock ${available?"":"out"}">${available?`متوفر للحجز · ${p.quantity} قطعة`:"غير متوفر حاليًا"}</span><div class="product-rating"><strong>★ ${Number(p.reviewAverage||0).toFixed(1)}</strong><span>${p.reviewCount||0} تقييم موثق بعد التسليم · بيع ${p.soldCount||0}</span></div><div class="specs"><div><strong>الخامة</strong>خشب مختار بعناية</div><div><strong>التشطيب</strong>يدوي مقاوم للاستخدام</div><div><strong>المخزون</strong>${p.quantity} قطعة</div><div><strong>المعاينة</strong>${frames.length>1?`عرض 360° من ${frames.length} صور`:"صورة واضحة للمنتج"}</div></div><form id="orderForm" class="order-form"><div><label>الكمية<input name="quantity" id="quantity" type="number" min="1" max="${p.quantity}" value="1" required></label><label>طريقة الدفع<input value="نقدًا فقط" disabled><input type="hidden" name="paymentMethod" value="نقدًا"></label></div><label>عنوان التوصيل<input name="address" required value="${esc([user.city,user.address].filter(Boolean).join(" - "))}"></label><label>ملاحظات<textarea name="notes" placeholder="اللون أو المقاس أو وقت التواصل"></textarea></label><div class="total-line" id="totalLine">الإجمالي: <strong>${money(store.priceInfo(p,1).final)}</strong></div><div class="actions"><button class="btn primary" ${available?"":"disabled"}>${available?"احجز المنتج":"غير متوفر"}</button><button type="button" id="addCart" class="btn secondary" ${available?"":"disabled"}>أضف للسلة</button><button type="button" id="favorite" class="btn secondary">إضافة للمفضلة ♡</button></div></form><div id="orderResult"></div>${reviews.length?`<div class="product-reviews"><h3>تقييمات بعد التسليم</h3>${reviews.slice(0,6).map(r=>`<article><strong>${"★".repeat(r.rating)}${"☆".repeat(5-r.rating)}</strong><span>${esc(r.customerName||"عميل ESPAN")}</span><p>${esc(r.comment||"تقييم بدون تعليق")}</p></article>`).join("")}</div>`:""}</section></div>`;
  let rotation=0,drag=false,startX=0,base=0;
  const viewer=document.getElementById("viewer"),img=document.getElementById("productImage"),angle=document.getElementById("angle");
  frames.forEach(src=>{const preload=new Image();preload.src=src});
  function render(){const normalized=((rotation%360)+360)%360,index=Math.round(normalized/360*frames.length)%frames.length;img.src=frames[index];angle.textContent=Math.round(normalized)+"°"}
  if(frames.length>1){viewer.addEventListener("pointerdown",e=>{drag=true;startX=e.clientX;base=rotation;viewer.setPointerCapture(e.pointerId)});viewer.addEventListener("pointermove",e=>{if(drag){rotation=base+(e.clientX-startX)*.8;render()}});viewer.addEventListener("pointerup",e=>{drag=false;if(viewer.hasPointerCapture(e.pointerId))viewer.releasePointerCapture(e.pointerId)});viewer.addEventListener("pointercancel",()=>drag=false)}
  render();
  function toast(m){const el=document.getElementById("toast");el.textContent=m;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
  document.getElementById("quantity").oninput=e=>{const q=Math.max(1,Number(e.target.value||1));const current=store.priceInfo(p,q);document.getElementById("unitPrice").textContent=money(current.final);document.getElementById("totalLine").innerHTML=`الإجمالي: <strong>${money(current.final*q)}</strong>${current.offer?`<small>${current.eligible?` — تم تطبيق العرض`:` — العرض يبدأ من ${current.minQuantity} قطع`}</small>`:""}`;};
  document.getElementById("addCart").onclick=async()=>{const q=Math.max(1,Number(document.getElementById("quantity").value||1));try{await store.addToCartAsync(p.id,q);toast("تمت الإضافة للسلة");}catch(err){toast(err.message||"تعذر الإضافة للسلة");}};
  document.getElementById("favorite").onclick=async()=>{try{const result=await store.toggleFavoriteAsync(p.id);toast(result.favorite?"تمت الإضافة للمفضلة":"تمت الإزالة من المفضلة");}catch(err){toast(err.message||"تعذر تحديث المفضلة");}};
  document.getElementById("orderForm").onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.paymentMethod="نقدًا";const button=e.currentTarget.querySelector("button[type=submit]");try{button.disabled=true;const result=await store.createOrderAsync({...values,productId:p.id,quantity:Number(values.quantity)});toast(`تم إنشاء الطلب ${result.order.id}`);document.getElementById("orderResult").innerHTML=`<div class="success-note">تم إرسال الطلب إلى لوحة الإدارة بنجاح.</div>`;}catch(err){button.disabled=false;toast(err.message||"تعذر إنشاء الطلب");}};
}());
